// <auto-generated />
namespace Prep2Plate.Migrations.UserMgmt
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingCalendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingCalendar));
        
        string IMigrationMetadata.Id
        {
            get { return "201712020412387_AddingCalendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
